### ISSUE TITLE
WorkFlowy 已经支持双链功能

### ISSUE THREAD

**Issue by BettyJJ** [eastlakeside/awesome-productivity-cn#6]
而且对于 Dynalist 的评价有些主观了，似乎评定它已超越了 WorkFlowy，但两者各有拥趸，见仁见智
建议修改

**Comment by suqi** [comment]
@BettyJJ  好的，有道理，我改的中肯一定

话说 Workflowy 的功能还有哪些没有被 Dynalist 覆盖的？ 我好奇一下

**Comment by suqi** [comment]
关于双链，对新笔记进行了注解

**Comment by BettyJJ** [comment]
可能还有镜像（就是 Roam 的块嵌入）
Roam 大热后，WF 把 Roam 的功能也渐渐都加上了
Dynalist 的团队则新开了一个项目 Obsidian，Dynalist 就不怎么加新功能了
WF 现在也能传图片了，功能上基本没什么缺陷了
